name = "augment-token-proxy"
main = "workers/token-proxy.ts"
compatibility_date = "2024-12-01"

[vars]
ALLOWED_ORIGINS = "*"
TENANT_URL_WHITELIST = "https://d"

[observability]
enabled = true

[[rules]]
type = "Text"
globs = ["**/*.html"]

